import Navbar from "@/components/Navbar";
import "./globals.css";
import Header from "@/components/Header.jsx"
import Navbar from "@/components/Navbar.jsx"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
